# Site settings
title: My jekyll blog site
email: adam.overstreet@gmail.com
description: A really cool blog!
url: "http://adamoverstreet.com/blog/" # the base hostname & protocol for your site
twitter_username: aunderroad

TZ: America/New_York  # Time Zone

# Build settings
markdown: kramdown
permalink: /:title # pretty
paginate: 2


#defaults settings
defaults:
-
    scope:
        path: "" # an empty string here means all files in the project
        type: "posts"  
    values:
        layout: "post"
        author: Adam Overstreet
        categories: conferences
        comments: true
-
    scope:
        path: "" # an empty string here means all files in the project
        type: "pages"  
    values:
        layout: "page"
-
    scope:
        path: "" # an empty string here means all files in the project
        type: "drafts"  
    values:
        layout: "post"
        categories: draft
